# Generated by Django 3.2.7 on 2021-10-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=25)),
                ('raas_version', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_hc', models.CharField(max_length=25)),
                ('type_of_activity', models.CharField(max_length=25)),
                ('fetch_fresh_logs', models.IntegerField()),
                ('name_of_project', models.CharField(max_length=25)),
            ],
        ),
    ]
